### ISSUE TITLE
Texture Acquisition

### ISSUE THREAD

**Issue by dwitmerRX2** [RazorX2/vrgame#1]
Find texture assets to import into the VR Game.

Walls, Floors, Carpet, windows, furniture.

**Comment by SishaarRao** [comment]
1. https://www.assetstore.unity3d.com/en/#!/content/15691
   Full Background, Easy Customization, Interactive Doors, Good Reviews
   $20

**Comment by vishaltandale00** [comment]
Work station desks
https://www.assetstore.unity3d.com/en/#!/content/59198
2$

**Comment by vishaltandale00** [comment]
Office Chair
https://www.assetstore.unity3d.com/en/#!/content/21466
5$

**Comment by SishaarRao** [comment]
https://www.assetstore.unity3d.com/en/#!/content/7674
Chair Alternative
$2

**Comment by vishaltandale00** [comment]
Center office table
https://www.assetstore.unity3d.com/en/#!/content/11859

**Comment by SishaarRao** [comment]
https://www.assetstore.unity3d.com/en/#!/content/5977
Center Office Table
Free

**Comment by vishaltandale00** [comment]
Office set has good work stations
https://www.assetstore.unity3d.com/en/#!/content/64864
4$

**Comment by dwitmerRX2** [comment]
https://www.assetstore.unity3d.com/en/#!/content/5977
Free.

**Comment by SishaarRao** [comment]
https://www.assetstore.unity3d.com/en/#!/content/20305

Stool, 3 legs,
$5

**Comment by SishaarRao** [comment]
https://www.assetstore.unity3d.com/en/#!/content/6930

Plant, Free

**Comment by SishaarRao** [comment]
https://www.assetstore.unity3d.com/en/#!/content/6411
Collection of Chairs
Free

**Comment by SishaarRao** [comment]
https://www.assetstore.unity3d.com/en/#!/content/53735
Office Props
Free

**Comment by dwitmerRX2** [comment]
Please create a final comment with a list view of the chosen assets for readability before we close this issue.
