### ISSUE TITLE
3D Modelling - Measure rooms to scale.

### ISSUE THREAD

**Issue by dwitmerRX2** [RazorX2/vrgame#2]
Measure Intern Lab and Main office area.

**Comment by dwitmerRX2** [comment]
Please put the measurements in the comments section as well.

**Comment by vishaltandale00** [comment]
[Measurements.docx](https://github.com/RazorX2/vrgame/files/354263/Measurements.docx)

**Comment by jpakRX2** [comment]
Nice. I like the level of detail on the measurements ... My last name is Pak, btw. 😉

**Comment by vishaltandale00** [comment]
Sorry,
Just fixed it

**Comment by frostme** [comment]
If there's a more updated measurements attachment, please attach here (with new version number), or if these are the final agreed upon measurements to scale, please note it here before we mark it as Closed.
