### ISSUE TITLE
Research 3D Modelling Software

### ISSUE THREAD

**Issue by dwitmerRX2** [RazorX2/vrgame#3]
Figure out which software to use.  Maya, Blender, etc.

**Comment by prounder** [comment]
blender—free+commercial, powerful, unity pipeline, lots of community support, makehuman middletool

but also a steep learning curve... same for alternatives though

**Comment by dwitmerRX2** [comment]
If this is the general consensus of the team, please note it here before we mark it as Closed.

**Comment by prounder** [comment]
the group has agreed on Blender and has begun using it for the models.
