### ISSUE TITLE
Asset characteristics

### ISSUE THREAD

**Issue by dwitmerRX2** [RazorX2/vrgame#6]
Determine out purpose, role, powers, actions, statistics.

**Comment by vishaltandale00** [comment]
Flying Enemy
Purpose: The flying viruses will be like a higher level bulkier virus that will become common in the later levels to increase difficulty
Role: To act as an elusive bulky virus
Actions: It can sting you with critical damage and show low damage “missiles” at you
Statistics: it will have 150 HP, 150 Speed Points, 100 attack

Floor-Level
Purpose: This will be a slow, light weight virus that will be easy to kill. At first they will come in small groups to act as a low difficulty. In the later levels they will come in swarms to increase difficulty
Role: To be low power easy kills
Actions: Can only physical claw at you which is a very low power
Statistics: 50 HP, 50 Speed, 25 Attack

Mid/Eye Level Enemy
Purpose: Will be decently strong and bulky enemies to act a slight challenge
Role: Enemies that act as a transition from lower levels to higher ones
Actions: able to shoot low damage missiles from a decent proximity
Statistics: 100 HP, 25 Speed, 75 Attack

**Comment by frostme** [comment]
If this is the general consensus of the team, please note it here before we mark it as Closed.
